agent:
  rollouts: 32
  learning_epochs: 4
  mini_batches: 64
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.00015001490150029674
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  entropy_loss_scale: 0.0
  value_loss_scale: 1.0
  kl_threshold: 0

ssl_task:
  type: "forward_dynamics"
  tactile_only: True
  loss_weight: 0.701442305058738
  learning_rate: 0.0007355855634320232
  n_rollouts: 1
  seq_length: 3

experiment:
  experiment_name: "tactile_dynamics"
  wandb: 1
  wandb_kwargs: {
    "group": "tactile_dynamics",
    "name": "null",
  }