agent:
  rollouts: 16
  learning_epochs: 17
  mini_batches: 32
  discount_factor: 0.99
  lambda: 0.9444170963776642
  learning_rate: 0.0000021253083066831893
  grad_norm_clip: 1.0
  ratio_clip:  0.18679645804380027
  value_clip: 0.24110103352262544
  entropy_loss_scale: 0.09966116999499125
  value_loss_scale: 0.4251937999099069
  kl_threshold: 0

ssl_task:
  type: "reconstruction"
  n_rollouts: 1
  tactile_only: True
  loss_weight: 0.0637643368107641
  learning_rate: 0.00008379929553630154
  learning_epochs_ratio: 0.25

experiment:
  experiment_name: "tac_recon"
  wandb: 1
  wandb_kwargs: {
    "group": "tac_recon",
    "name": "1",
  }