agent:
  rollouts: 16
  learning_epochs: 12
  mini_batches: 16
  discount_factor: 0.99
  lambda: 0.9496027438984123
  learning_rate: 1.2547750505541669e-05
  grad_norm_clip: 1.0
  ratio_clip: 0.1531550806661562
  value_clip: 0.13570193261993407
  value_loss_scale: 0.5908736561480681
  entropy_loss_scale: 0.054197310404172146
  kl_threshold: 0

ssl_task:
  type: "forward_dynamics"
  n_rollouts: 1
  tactile_only: False
  loss_weight: 0.0019029953381059972
  learning_rate: 0.00016180128638146235
  seq_length: 7
  learning_epochs_ratio: 0.25

experiment:
  experiment_name: "forward_dynamics"
  wandb: 1
  wandb_kwargs: {
    "group": "forward_dynamics",
    "name": "1",
  }