agent:
  rollouts: 16
  learning_epochs: 14
  mini_batches: 16
  discount_factor: 0.99
  lambda: 0.907232209016445
  learning_rate: 8.571638417056478e-05
  grad_norm_clip: 1.0
  ratio_clip: 0.15780009343526674
  value_clip: 0.2018937033984739
  value_loss_scale: 0.8381938759726169
  entropy_loss_scale: 0.2551308863496997
  kl_threshold: 0

ssl_task:
  type: "forward_dynamics"
  n_rollouts: 1
  tactile_only: True
  loss_weight: 0.0024563011888180755
  learning_rate: 0.00015653936173824111
  seq_length: 4

experiment:
  experiment_name: "tactile_dynamics"
  wandb: 1
  wandb_kwargs: {
    "group": "tactile_dynamics",
    "name": "1",
  }