agent:
  rollouts: 64
  learning_epochs: 8
  mini_batches: 32
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 2.2023161423384864e-05
  ratio_clip: 0.2
  value_clip: 0.2
  entropy_loss_scale: 0.05
  value_loss_scale: 1.0
  kl_threshold: 0
  grad_norm_clip: 1.0

ssl_task:
  type: "forward_dynamics"
  n_rollouts: 1
  tactile_only: False
  loss_weight: 0.0024563011888180755
  learning_rate: 0.00015653936173824111
  seq_length: 4

experiment:
  experiment_name: "forward_dynamics"
  save_checkpoints: 1
  tb_log: 1
  wandb: 1
  wandb_kwargs: {
    "group": "forward_dynamics",
    "name": "test",
  }