agent:
  rollouts: 32
  learning_epochs: 20
  mini_batches: 16
  discount_factor: 0.99
  lambda: 0.9066813033152197
  value_clip: 0.203740908288308
  ratio_clip: 0.13500339418789895
  kl_threshold: 0
  learning_rate: 9.238029902773938e-05
  entropy_loss_scale: 0.0010332144235249002
  value_loss_scale: 0.6264567935379245
  grad_norm_clip: 1.0

experiment:
  experiment_name: "rl_only_pt"
  save_checkpoints: 1
  tb_log: 1
  wandb: 0
  wandb_kwargs: {
    "group": "rl_only_pt",
    "name": "1",
  }
