agent:
  rollouts: 32
  learning_epochs: 6
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.9468143653146185
  learning_rate: 3.1739162635257763e-06
  grad_norm_clip: 1.0
  ratio_clip: 0.2359054267575137
  value_clip: 0.19126743895843024
  value_loss_scale: 0.3068963415215419
  entropy_loss_scale: 0.4239605567690041
  kl_threshold: 0

ssl_task:
  type: "forward_dynamics"
  n_rollouts: 1
  tactile_only: False
  loss_weight: 0.025075893990136915
  learning_rate: 0.00025205565044316406
  seq_length: 2
  learning_epochs_ratio: 1.0

experiment:
  experiment_name: "Bounce_forward_dynamics_seeded"
  wandb: 1
  wandb_kwargs: {
    "group": "Bounce_forward_dynamics_seeded",
    "name": "1",
  }